//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessors
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiotAPILeague
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiotAPILeague()
        {
            this.RiotAPILeagueEntries = new HashSet<RiotAPILeagueEntry>();
        }
    
        public int RiotAPILeagueID { get; set; }
        public long RiotAPISummonerID { get; set; }
        public string LeagueName { get; set; }
        public string QueueType { get; set; }
        public string Tier { get; set; }
    
        public virtual RiotAPISummoner RiotAPISummoner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiotAPILeagueEntry> RiotAPILeagueEntries { get; set; }
    }
}
