//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toxic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toxic()
        {
            this.CoachSignUps = new HashSet<CoachSignUp>();
            this.StudentSignUps = new HashSet<StudentSignUp>();
        }
    
        public int ToxicID { get; set; }
        public int ToxicLevel { get; set; }
        public bool HadLowPriorityPunish { get; set; }
        public bool HadChatRestriction { get; set; }
        public bool HadRankedRestrictions { get; set; }
        public bool HadTemporaryBan { get; set; }
        public bool HadPermanentBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoachSignUp> CoachSignUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSignUp> StudentSignUps { get; set; }
    }
}
