//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachSignUp
    {
        public int CoachSignUpID { get; set; }
        public int CoachStatus { get; set; }
        public int SummonerInfoID { get; set; }
        public string InterestedRank { get; set; }
        public bool WillingBronze { get; set; }
        public bool WillingSilver { get; set; }
        public bool WillingGold { get; set; }
        public bool WillingPlat { get; set; }
        public bool WillingDiamond { get; set; }
        public int AvailabilityID { get; set; }
        public string Languages { get; set; }
        public string PairedPlayers { get; set; }
        public string CoachingStyle { get; set; }
        public string CoachingExperience { get; set; }
        public int CommitmentID { get; set; }
        public int ToxicID { get; set; }
        public string MoreInformation { get; set; }
        public bool EmailSignUp { get; set; }
    
        public virtual AvailabilityInfo AvailabilityInfo { get; set; }
        public virtual SummonerInfo SummonerInfo { get; set; }
        public virtual Commitment Commitment { get; set; }
        public virtual Toxic Toxic { get; set; }
    }
}
