//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearningFivesEntities : DbContext
    {
        public LearningFivesEntities()
            : base("name=LearningFivesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityInfo> AvailabilityInfoes { get; set; }
        public virtual DbSet<Commitment> Commitments { get; set; }
        public virtual DbSet<RoleInfo> RoleInfoes { get; set; }
        public virtual DbSet<StudentSignUp> StudentSignUps { get; set; }
        public virtual DbSet<SummonerInfo> SummonerInfoes { get; set; }
        public virtual DbSet<Toxic> Toxics { get; set; }
        public virtual DbSet<CoachSignUp> CoachSignUps { get; set; }
    }
}
