//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleInfo()
        {
            this.StudentSignUps = new HashSet<StudentSignUp>();
        }
    
        public int RoleInfoID { get; set; }
        public string PreferredRole { get; set; }
        public int TopLaneComfort { get; set; }
        public int JungleComfort { get; set; }
        public int MidComfort { get; set; }
        public int MarksmanComfort { get; set; }
        public int SupportComfort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSignUp> StudentSignUps { get; set; }
    }
}
